<a href="https://colab.research.google.com/github/RiteshopShrivastava/Python/blob/main/Exercise_Complete_Numpy_Tutorial_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [14]:
python_list = [ i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.001529759000000297


In [68]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(start_time - end_time)


-0.0005885069999997938


Numpy Arrays

In [16]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [17]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [18]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [19]:
a.shape

(4,)

In [20]:
b= np.array([(1,2,3,4), (5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
b.shape

(2, 4)

In [25]:
c = np.array([(1,2,3,4),(5,6,7,8)],float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [26]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [29]:
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [32]:
z = np.full((4,5),6)
print(z)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [ ]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.06180442 0.35700298 0.90695408 0.03091635]
 [0.58655837 0.66048197 0.29741526 0.89522409]
 [0.75529751 0.8197227  0.89382064 0.85936446]]


In [36]:
b = np.random.random((3,5))
print(b)

[[0.61622721 0.29937452 0.50518759 0.27598615 0.12539674]
 [0.08869929 0.28297088 0.21666896 0.61289435 0.68788743]
 [0.90931367 0.04000967 0.3686506  0.49157366 0.69023699]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[24 82 43 91 73]
 [98 11 52 38 38]
 [13 68 44 21 11]]


In [39]:
c = np.random.randint(10,30,(3,5))
print(c)

[[16 17 16 12 11]
 [26 25 22 18 14]
 [29 22 13 10 28]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [41]:
d = np.linspace(10,40,10)
print(d)

[10.         13.33333333 16.66666667 20.         23.33333333 26.66666667
 30.         33.33333333 36.66666667 40.        ]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [43]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [48]:
list3 = [10,20,30,40,50]
print("type of list is ", type(list3))

np_array = np.array(list3)
print(np_array)
type(np_array)

type of list is  <class 'list'>
[10 20 30 40 50]


numpy.ndarray

Analysing a numpy array

In [49]:
c = np.random.randint(10,90,(5,5))
print(c)

[[20 54 78 78 77]
 [25 43 33 29 14]
 [83 10 31 25 30]
 [88 64 49 36 74]
 [59 75 28 12 75]]


In [50]:
# array dimension
print(c.shape)

(5, 5)


In [51]:
# number of dimensions
print(c.ndim)

2


In [52]:
# number of elements in an array
print(c.size)

25


In [53]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [54]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [55]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [56]:
print(a)
print(b)

[[8 2 2]
 [2 4 4]
 [3 7 5]]
[[19 13 12]
 [11 14 19]
 [12 15 19]]


In [57]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[27 15 14]
 [13 18 23]
 [15 22 24]]
[[-11 -11 -10]
 [ -9 -10 -15]
 [ -9  -8 -14]]
[[152  26  24]
 [ 22  56  76]
 [ 36 105  95]]
[[0.42105263 0.15384615 0.16666667]
 [0.18181818 0.28571429 0.21052632]
 [0.25       0.46666667 0.26315789]]


In [58]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [59]:
print(a)
print(b)

[[3 2 1]
 [9 0 2]
 [4 5 5]]
[[11 17 10]
 [17 14 14]
 [11 18 17]]


In [60]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[14 19 11]
 [26 14 16]
 [15 23 22]]
[[ -8 -15  -9]
 [ -8 -14 -12]
 [ -7 -13 -12]]
[[ 33  34  10]
 [153   0  28]
 [ 44  90  85]]
[[0.27272727 0.11764706 0.1       ]
 [0.52941176 0.         0.14285714]
 [0.36363636 0.27777778 0.29411765]]


Array Manipulation

In [61]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 2 7]
 [4 2 7]]
(2, 3)


In [62]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 4]
 [2 2]
 [7 7]]
(3, 2)


In [63]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 5 4]
 [9 2 8]]
(2, 3)


In [64]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 9]
 [5 2]
 [4 8]]
(3, 2)


In [66]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 5 9]
 [0 5 4]]
(2, 3)


In [67]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[0 5]
 [9 0]
 [5 4]]
(3, 2)
